import Navbar from "./components/Navbar";
import "./style.css";
import UserContext from "@/Context/UserContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserContext>
        <body suppressHydrationWarning={true}>
          <main className="w-full min-h-[100vh] ">
            <Navbar />
            {children}
          </main>
        </body>
      </UserContext>
    </html>
  );
}
